#!/bin/bash
# PORTMASTER: skate3, Skateboard Party 3.sh
# Skateboard Party 3 — generated by nxbootstrap 0.6.26.
NXBOOTSTRAP_FINISHED=0
NXBOOTSTRAP_ABORTING=0
NXBOOTSTRAP_EARLY_LOG_ACTIVE=1
NXBOOTSTRAP_LAUNCHER_DIR=""
nxbootstrap_finish() {
  [ "$NXBOOTSTRAP_FINISHED" = 0 ] || return 0
  NXBOOTSTRAP_FINISHED=1
  if command -v pm_finish >/dev/null 2>&1; then pm_finish || true; fi
}
nxbootstrap_write_early_log() {
  local status=$1 log_dir log_path
  [ "$NXBOOTSTRAP_EARLY_LOG_ACTIVE" = 1 ] && [ "$status" -ne 0 ] 2>/dev/null || return 0
  for log_dir in "${GAMEDIR:-}" "$NXBOOTSTRAP_LAUNCHER_DIR" \
    "${XDG_RUNTIME_DIR:-}" "${TMPDIR:-/tmp}"; do
    [ -n "$log_dir" ] && [ -d "$log_dir" ] && [ ! -L "$log_dir" ] || continue
    log_path="$log_dir/skate3-launcher-error.$$.log"
    if (umask 077; set -C; printf '%s\n' \
      '== Skateboard Party 3 | nxbootstrap 0.6.26 | pre-runtime failure ==' \
      "status=$status pid=$$" "launcher=${BASH_SOURCE[0]:-$0}" \
      "game_dir=${GAMEDIR:-unresolved}" "cfw=${CFW_NAME:-unknown}" > "$log_path") 2>/dev/null; then
      printf 'nxbootstrap: pre-runtime failure; log=%s\n' "$log_path" >&2
      return 0
    fi
  done
  printf 'nxbootstrap: pre-runtime failure; no writable diagnostic path\n' >&2
}
nxbootstrap_on_exit() {
  local status=$1
  nxbootstrap_write_early_log "$status"
  nxbootstrap_finish
  return "$status"
}
nxbootstrap_install_exit_trap() {
  trap 'nxbootstrap_on_exit $?' EXIT
}
nxbootstrap_abort_before_game() {
  local abort_status=$1
  [ "$NXBOOTSTRAP_ABORTING" = 0 ] || return 0
  NXBOOTSTRAP_ABORTING=1
  echo "== aborted before game start (status $abort_status) =="
  nxbootstrap_finish
  exit "$abort_status"
}
nxbootstrap_install_early_traps() {
  trap 'nxbootstrap_abort_before_game 130' INT
  trap 'nxbootstrap_abort_before_game 143' TERM
  trap 'nxbootstrap_abort_before_game 129' HUP
}
nxbootstrap_install_exit_trap

# A signal before the game starts (mapper/extraction can take seconds) must
# still hand the screen back to the frontend instead of dying by default.
nxbootstrap_install_early_traps

# The EXIT trap is deliberately live before path discovery, PortMaster, controls
# or any other command that can fail.  Resolve the visible launcher only now.
NXBOOTSTRAP_LAUNCHER_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd -P) || \
  NXBOOTSTRAP_LAUNCHER_DIR=""


XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
# Language / Idioma (supported / suportados: en, pt, es, fr, de, it, ru, ko, zh).
# Edit only this value; adapters opt in through nxport.json.
GAME_LANGUAGE="en"
case "$GAME_LANGUAGE" in
  auto|en|pt|es|fr|de|it|ru|ko|zh) ;;
  *) GAME_LANGUAGE="auto" ;;
esac
NXPORT_LANGUAGE=${NXPORT_LANGUAGE:-$GAME_LANGUAGE}
case "$NXPORT_LANGUAGE" in
  auto|en|pt|es|fr|de|it|ru|ko|zh) ;;
  *) NXPORT_LANGUAGE=$GAME_LANGUAGE ;;
esac
NXBOOTSTRAP_LANGUAGE=$NXPORT_LANGUAGE
export NXPORT_LANGUAGE


# PortMaster publishes the integrated handheld stick count as ANALOGSTICKS;
# some CFW adapters use ANALOG_STICKS. Keep it as a validated host hint only:
# per-controller SDL bindings remain the authority for actual capabilities.
NXBOOTSTRAP_ANALOG_STICKS_HINT=""
unset NXINPUT_ANALOG_STICKS_HINT

# Safe CFW identity is diagnostic/mod-selection context only, never a quirk.
nxbootstrap_observe_cfw_name() {
  local candidate=""
  case "${CFW_NAME-}" in *[!A-Za-z0-9._-]*|'') unset CFW_NAME ;; *) return 0 ;; esac
  if [ -n "${HOME:-}" ] && [ -f "$HOME/.config/.OS" ] && \
     [ ! -L "$HOME/.config/.OS" ]; then
    IFS= read -r -n 65 candidate < "$HOME/.config/.OS" || true
  fi
  [ "${#candidate}" -le 64 ] || candidate=""
  case "$candidate" in *[!A-Za-z0-9._-]*|'') candidate="" ;; esac
  # dArkOSRE omits .OS: require two independent regular firmware artifacts.
  if [ -z "$candidate" ] && \
     [ -f /boot/arkos4clone-uboot.dtb ] && [ ! -L /boot/arkos4clone-uboot.dtb ] && \
     [ -f "/opt/system/Advanced/Backup dArkOS Settings.sh" ] && [ ! -L "/opt/system/Advanced/Backup dArkOS Settings.sh" ]; then
    candidate=dArkOSRE
  fi
  # ArkOS/TheRA/RetroOZ publish their identity in the plymouth title (same
  # source as PortMaster's device_info.txt); ELEC/JELOS/ROCKNIX/muOS/Knulli in
  # os-release OS_NAME/NAME. Plain ArkOS used to log cfw=none without .OS.
  local pfile=/usr/share/plymouth/themes/text.plymouth
  if [ -z "$candidate" ] && [ -f "$pfile" ] && [ ! -L "$pfile" ]; then
    candidate=$(grep -a -m1 '^title=' "$pfile" 2>/dev/null | cut -d= -f2- | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
  fi
  if [ -z "$candidate" ] && [ -f /etc/os-release ] && [ ! -L /etc/os-release ]; then
    candidate=$(grep -a -m1 '^OS_NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
    [ -n "$candidate" ] || candidate=$(grep -a -m1 '^NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"' | cut -d' ' -f1 | tr -cd 'A-Za-z0-9._-' | cut -c1-64)
    case "$candidate" in Debian|Ubuntu|Linux|Buildroot) candidate="" ;; esac
  fi
  case "$candidate" in *[!A-Za-z0-9._-]*|'') candidate="" ;; esac
  [ -n "$candidate" ] && CFW_NAME=$candidate
}
nxbootstrap_observe_cfw_name
# Find a real control.txt instead of stopping at the first empty PortMaster
# directory. The roots mirror the supported PortMaster/CFW layouts; the first
# valid regular control file keeps precedence.
controlfolder=""
NXBOOTSTRAP_PM_ROOTS=(
  "/opt/system/Tools/PortMaster" "/opt/tools/PortMaster"
  "$XDG_DATA_HOME/PortMaster" "/storage/.config/PortMaster"
  "/var/data/PortMaster" "/PortMaster"
  "/roms/tools/PortMaster" "/roms2/tools/PortMaster"
  "/storage/roms/ports/PortMaster" "/storage/roms/Ports/PortMaster"
  "/roms/ports/PortMaster" "/roms/Ports/PortMaster"
  "/roms2/ports/PortMaster" "/roms2/Ports/PortMaster"
  "/userdata/roms/ports/PortMaster"
  "/userdata/system/.local/share/PortMaster"
  "/mnt/ports/PortMaster" "/mnt/Ports/PortMaster"
  "/mnt/mmc/MUOS/PortMaster" "/mnt/mmc/ports/PortMaster"
  "/mnt/SDCARD/Apps/PortMaster/PortMaster"
  "/mnt/sdcard/Roms/.portmaster/PortMaster"
)
for NXBOOTSTRAP_PM_CANDIDATE in "${NXBOOTSTRAP_PM_ROOTS[@]}"; do
  [ -f "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] || continue
  NXBOOTSTRAP_PM_REAL=$(readlink -f "$NXBOOTSTRAP_PM_CANDIDATE" 2>/dev/null) || continue
  [ -d "$NXBOOTSTRAP_PM_REAL" ] && \
    [ -f "$NXBOOTSTRAP_PM_REAL/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_REAL/control.txt" ] || continue
  controlfolder=$NXBOOTSTRAP_PM_REAL
  break
done
unset NXBOOTSTRAP_PM_ROOTS NXBOOTSTRAP_PM_CANDIDATE NXBOOTSTRAP_PM_REAL
[ -n "$controlfolder" ] || controlfolder="/storage/.config/PortMaster"

# Sourced firmware files must be regular (a symlinked control.txt/mod can
# point anywhere), and CFW_NAME reaches a source path so it must never carry
# a separator or shell-hostile byte.
if [ -f "$controlfolder/control.txt" ] && [ ! -L "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  nxbootstrap_install_exit_trap
  nxbootstrap_install_early_traps
  nxbootstrap_observe_cfw_name
  case "${CFW_NAME-}" in
    *[!A-Za-z0-9._-]*|'') NXBOOTSTRAP_MOD_NAME='' ;;
    *) NXBOOTSTRAP_MOD_NAME=$CFW_NAME ;;
  esac
  if [ -n "$NXBOOTSTRAP_MOD_NAME" ] && \
     [ -f "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ] && \
     [ ! -L "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ]; then
    source "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt"
    nxbootstrap_install_exit_trap
    nxbootstrap_install_early_traps
  fi
  command -v get_controls >/dev/null 2>&1 && get_controls
  case "${ANALOGSTICKS:-${ANALOG_STICKS:-}}" in
    0|1|2)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=${ANALOGSTICKS:-${ANALOG_STICKS:-}}
      export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT"
      ;;
    *)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=""
      unset NXINPUT_ANALOG_STICKS_HINT
      ;;
  esac
  nxbootstrap_install_exit_trap
  nxbootstrap_install_early_traps
  export NXCOMPAT_PORTMASTER_DIR="$controlfolder"
else
  unset NXCOMPAT_PORTMASTER_DIR
fi

GAMEDIR="/$directory/ports/skate3"
[ -d "$GAMEDIR" ] || GAMEDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)/skate3"
# Physical path: ROM roots are often symlinks (/roms -> /storage/roms) and
# tools that compare canonical containment would reject the logical path.
cd "$GAMEDIR" || exit 1
GAMEDIR=$(pwd -P)

# Record whether this run could put an image on the panel at all.  A launch
# from a remote shell can fail to open a window for reasons that have nothing
# to do with the game, and a black frame collected that way is evidence about
# the harness, not the port.  The frontend starts us with no SSH_* in the
# environment; a remote operator always carries them.
if [ -z "$SSH_CONNECTION" ] && [ -z "$SSH_TTY" ] && [ -z "$SSH_CLIENT" ]; then
  export NXLAUNCH_FRONTEND=1
fi

[ -s "$GAMEDIR/log.txt" ] && mv -f "$GAMEDIR/log.txt" "$GAMEDIR/log.prev.txt" 2>/dev/null
if ! exec > "$GAMEDIR/log.txt" 2>&1; then
  printf 'nxbootstrap: cannot open the runtime log\n' >&2
  exit 1
fi
if ! echo "== Skateboard Party 3 | nxbootstrap 0.6.26 | cfw=${CFW_NAME:-none} =="; then
  exit 1
fi
NXBOOTSTRAP_EARLY_LOG_ACTIVE=0

# Durable latest-boundary record.  Every transition is published by an
# exclusive temporary file and rename before the following phase can begin.
# Runtime adapters receive the same schema/path and remain the authority for
# video-provider and first-frame observations; the launcher never fabricates
# either event or inserts a pipe into the native process flow.
NXBOOTSTRAP_PHASE_SEQUENCE=0
NXBOOTSTRAP_PHASE_FILE="$GAMEDIR/nxphase-result.json"
NXOBS_PHASE_PROTOCOL=nxbootstrap-phase-v1
NXOBS_PHASE_FILE=$NXBOOTSTRAP_PHASE_FILE
NXOBS_EVENT_PROTOCOL=nx-event-v1
NXOBS_EVENT_SINK=stdout
NXOBS_RUN_ID=skate3-$$
NXOBS_BOOTSTRAP_VERSION=0.6.26
NXOBS_PHASE_SCHEMA_VERSION=1
export NXOBS_PHASE_PROTOCOL NXOBS_PHASE_FILE NXOBS_EVENT_PROTOCOL \
  NXOBS_EVENT_SINK NXOBS_RUN_ID NXOBS_BOOTSTRAP_VERSION \
  NXOBS_PHASE_SCHEMA_VERSION
nxbootstrap_phase_event() {
  local phase=$1 boundary=$2 source=$3 reason_code=$4 child_status=${5:-}
  local event_status phase_tmp child_json event_details
  case "$phase" in ''|*[!A-Za-z0-9._-]*) return 2 ;; esac
  case "$source" in
    bootstrap|extractor|loader|graphics|audio|input|lifecycle|diagnostic) ;;
    *) return 2 ;;
  esac
  case "$reason_code" in ''|*[!0-9]*) return 2 ;; esac
  [ "$reason_code" -le 9999 ] 2>/dev/null || return 2
  case "$boundary" in
    START) event_status=begin ;;
    OK) event_status=ok ;;
    ERROR) event_status=failed ;;
    OBSERVED) event_status=observed ;;
    EXIT)
      case "$child_status" in ''|*[!0-9]*) return 2 ;; esac
      if [ "$child_status" -eq 0 ]; then event_status=ok; else event_status=failed; fi
      ;;
    *) return 2 ;;
  esac
  case "$child_status" in
    '') child_json=null; event_details='{}' ;;
    *[!0-9]*) return 2 ;;
    *) child_json=$child_status; event_details="{\"child_status\":$child_status}" ;;
  esac
  if [ -L "$NXBOOTSTRAP_PHASE_FILE" ] || [ -d "$NXBOOTSTRAP_PHASE_FILE" ]; then
    echo "ERROR: phase result path is unsafe"
    return 1
  fi
  NXBOOTSTRAP_PHASE_SEQUENCE=$((NXBOOTSTRAP_PHASE_SEQUENCE + 1))
  phase_tmp="$GAMEDIR/.nxphase-result.json.tmp.$$.$NXBOOTSTRAP_PHASE_SEQUENCE.$RANDOM"
  if ! (umask 077; set -C; printf '%s\n' \
    "{\"schema\":\"org.nextos.nxbootstrap.phase-result\",\"schema_version\":1,\"nxbootstrap_version\":\"0.6.26\",\"sequence\":$NXBOOTSTRAP_PHASE_SEQUENCE,\"run_id\":\"skate3-$$\",\"source\":\"$source\",\"phase\":\"$phase\",\"boundary\":\"$boundary\",\"status\":\"$event_status\",\"reason_code\":$reason_code,\"child_status\":$child_json,\"pid\":$$}" \
    > "$phase_tmp" && mv -f "$phase_tmp" "$NXBOOTSTRAP_PHASE_FILE"); then
    rm -f "$phase_tmp" 2>/dev/null || true
    echo "ERROR: could not publish phase boundary: $phase $boundary"
    return 1
  fi
  if [ "$boundary" = EXIT ]; then
    printf 'PHASE %s EXIT status=%s\n' "$phase" "$child_status"
  else
    printf 'PHASE %s %s\n' "$phase" "$boundary"
  fi
  printf 'NXEVENT {"schema":"nx-event-v1","source":"%s","phase":"%s","status":"%s","reason_code":%s,"details":%s}\n' \
    "$source" "$phase" "$event_status" "$reason_code" "$event_details"
}

nxbootstrap_validate_nxextract_result() {
  python3 -B - "$1" "$2" <<'PY'
import json
import os
import re
import stat
import sys

sys.tracebacklimit = 0
path, process_status_text = sys.argv[1:]
process_status = int(process_status_text)
# Members born WITH schema_version 1 are required. Members added LATER in the
# same schema_version (ui, and any future addition) are validated only when
# present -- BOTH directions of a partially updated install keep working:
# old launcher + new engine (extra member ignored there) and new launcher +
# old engine (missing member tolerated here).
top_keys = {
    "schema", "schema_version", "nxextract_version", "outcome", "code",
    "final_phase", "recipe", "package_id", "abi", "container",
    "validated", "logs", "duration_ms", "completed_unix", "error",
}
phase_ids = (
    "preparing", "scanning", "validating-packages", "selecting",
    "extracting", "processing", "validating-data", "installing", "ready",
)
sha256_re = re.compile(r"^[0-9a-f]{64}$")
safe_id_re = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")

def reject(message):
    raise ValueError(message)

def pairs(items):
    result = {}
    for key, value in items:
        if key in result:
            reject("duplicate JSON member")
        result[key] = value
    return result

def finite_constant(_value):
    reject("non-finite JSON number")

def exact_object(value, keys, label):
    if not isinstance(value, dict) or set(value) != set(keys):
        reject("invalid " + label + " object")


def require_members(value, keys, label):
    # 0.6.26: FORWARD-COMPATIBLE. Every known member must be present and is
    # validated below, but EXTRA members added by a newer engine are ignored
    # instead of rejected -- adding a field is a compatible change. The real
    # compatibility contract is schema + schema_version, checked right after.
    if not isinstance(value, dict) or not set(keys) <= set(value):
        reject("invalid " + label + " object")

def integer(value, label):
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        reject("invalid " + label)

def string(value, minimum, maximum, label):
    if not isinstance(value, str) or not minimum <= len(value) <= maximum:
        reject("invalid " + label)
    if any(ord(char) < 32 for char in value):
        reject("control byte in " + label)

def relative_path(value, label):
    string(value, 1, 512, label)
    if value.startswith("/") or "\\" in value or ".." in value.split("/"):
        reject("invalid " + label)

flags = (os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) |
         getattr(os, "O_NOFOLLOW", 0))
fd = os.open(path, flags)
try:
    opened = os.fstat(fd)
    linked = os.lstat(path)
    if (not stat.S_ISREG(opened.st_mode) or opened.st_nlink != 1 or
            (opened.st_dev, opened.st_ino) != (linked.st_dev, linked.st_ino)):
        reject("unsafe result identity")
    chunks = []
    total = 0
    while True:
        block = os.read(fd, 65536)
        if not block:
            break
        total += len(block)
        if total > 1048576:
            reject("result exceeds size limit")
        chunks.append(block)
finally:
    os.close(fd)

document = json.loads(
    b"".join(chunks).decode("utf-8", "strict"),
    object_pairs_hook=pairs,
    parse_constant=finite_constant,
)
require_members(document, top_keys, "terminal result")
# The compatibility contract is the schema id + schema_version ONLY. A newer
# engine (any nxextract_version) that keeps schema_version 1 stays readable by
# this launcher -- so a partially-updated install (new engine under an older
# launcher .sh) no longer dies with "unknown terminal result schema". A real
# breaking change would bump schema_version, which this gate still rejects.
if (document["schema"] != "org.nextos.nxextract.terminal-result" or
        isinstance(document["schema_version"], bool) or
        document["schema_version"] != 1 or
        not isinstance(document["nxextract_version"], str) or
        re.fullmatch(r"[0-9]{1,4}\.[0-9]{1,4}\.[0-9]{1,4}",
                     document["nxextract_version"]) is None):
    reject("unknown terminal result schema")
if document["outcome"] not in ("success", "error"):
    reject("invalid terminal outcome")
if (process_status == 0) != (document["outcome"] == "success"):
    reject("process status and terminal outcome disagree")
if (not isinstance(document["code"], str) or
        not re.fullmatch(r"^NXE[0-9]{4}$", document["code"])):
    reject("invalid terminal code")

phase = document["final_phase"]
exact_object(phase, ("index", "id", "label"), "final phase")
integer(phase["index"], "phase index")
if phase["index"] > 8 or phase["id"] != phase_ids[phase["index"]]:
    reject("invalid final phase")
string(phase["label"], 1, 64, "phase label")

recipe = document["recipe"]
exact_object(recipe, ("id", "version", "digest"), "recipe")
if (not isinstance(recipe["id"], str) or
        not safe_id_re.fullmatch(recipe["id"])):
    reject("invalid recipe id")
string(recipe["version"], 1, 128, "recipe version")
if (not isinstance(recipe["digest"], str) or
        not sha256_re.fullmatch(recipe["digest"])):
    reject("invalid recipe digest")

if document["package_id"] is not None:
    string(document["package_id"], 1, 255, "package id")
abi = document["abi"]
if (abi is not None and
        (not isinstance(abi, str) or
         not re.fullmatch(r"^[A-Za-z0-9._-]{1,64}$", abi))):
    reject("invalid ABI")
container = document["container"]
exact_object(container, ("kind", "identity"), "container")
if container["kind"] not in (
        "apk-set", "bundle", "companion", "existing", None):
    reject("invalid container kind")
identity = container["identity"]
if (identity is not None and
        (not isinstance(identity, str) or not sha256_re.fullmatch(identity))):
    reject("invalid container identity")

validated = document["validated"]
exact_object(validated, ("items", "bytes", "critical_payloads"), "validated")
integer(validated["items"], "validated item count")
integer(validated["bytes"], "validated byte count")
critical = validated["critical_payloads"]
if not isinstance(critical, list) or len(critical) > 256:
    reject("invalid critical payload list")
for item in critical:
    exact_object(item, ("id", "items", "bytes"), "critical payload")
    if (not isinstance(item["id"], str) or
            not safe_id_re.fullmatch(item["id"])):
        reject("invalid critical payload id")
    integer(item["items"], "critical payload item count")
    integer(item["bytes"], "critical payload byte count")

logs = document["logs"]
exact_object(logs, ("summary", "detail"), "logs")
relative_path(logs["summary"], "summary log")
relative_path(logs["detail"], "detail log")
integer(document["duration_ms"], "duration")
integer(document["completed_unix"], "completion time")

if "ui" in document:
    ui = document["ui"]
    exact_object(ui, ("mode", "renderer", "fallback_reason"), "ui")
    if ui["mode"] not in ("visible", "headless-fallback", "disabled"):
        reject("invalid ui mode")
    if ui["renderer"] is not None:
        string(ui["renderer"], 1, 32, "ui renderer")
    if ui["fallback_reason"] is not None:
        string(ui["fallback_reason"], 1, 512, "ui fallback reason")
    if (ui["mode"] == "headless-fallback") != (
            ui["fallback_reason"] is not None):
        reject("ui mode and fallback reason disagree")

error = document["error"]
if document["outcome"] == "success":
    if error is not None:
        reject("success result contains an error")
else:
    exact_object(error, ("class", "message"), "error")
    if (not isinstance(error["class"], str) or
            not re.fullmatch(r"^[A-Za-z][A-Za-z0-9_]{0,127}$",
                             error["class"])):
        reject("invalid error class")
    string(error["message"], 1, 512, "error message")

print(json.dumps(document, ensure_ascii=True, sort_keys=True,
                 separators=(",", ":")))
PY
}

nxbootstrap_phase_event preflight START bootstrap 6190 || {
  nxbootstrap_finish
  exit 1
}

# The executable is itself required and is touched before the owner-data phase.
NXBOOTSTRAP_EXECUTABLE=$(readlink -f "$GAMEDIR/skate3-nextos" 2>/dev/null) || NXBOOTSTRAP_EXECUTABLE=""
case "$NXBOOTSTRAP_EXECUTABLE" in
  "$GAMEDIR"/*) ;;
  *) NXBOOTSTRAP_EXECUTABLE="" ;;
esac
if [ -z "$NXBOOTSTRAP_EXECUTABLE" ] || [ ! -f "$NXBOOTSTRAP_EXECUTABLE" ] || \
   [ ! -s "$NXBOOTSTRAP_EXECUTABLE" ] || [ -L "$GAMEDIR/skate3-nextos" ]; then
  echo "ERROR: executable is missing or unsafe: skate3-nextos"
  nxbootstrap_finish
  exit 1
fi

# Dynamic-loader (PT_INTERP) preflight: an ELF whose interpreter is absent
# exec()s with ENOENT, which the shell reports as "No such file or directory"
# for the binary and a bare status 127 -- a black screen that looks like a
# broken port but is a missing device runtime. Textbook case: a 32-bit ARMHF
# port on a 64-bit-only CFW with no 32-bit ARM runtime (spruce/Miyoo Flip:
# /lib/ld-linux-armhf.so.3 absent). `grep -a` reads the early .interp; a static
# or unreadable ELF yields nothing and skips the check (never a false block).
# Prefix that runs the game THROUGH an explicit loader (empty for every normal
# port -- the run line then executes "$BIN" byte-identically). Only set below,
# for the spruce/Miyoo-Flip case where the 32-bit loader lives off the default
# path.
NXBOOTSTRAP_INTERP_PREFIX=""
NXBOOTSTRAP_INTERP=$(LC_ALL=C grep -a -o -m1 -E '/lib(32|64)?/ld-[A-Za-z0-9._-]*\.so[A-Za-z0-9._-]*' "$NXBOOTSTRAP_EXECUTABLE" 2>/dev/null | head -n1)
if [ -n "$NXBOOTSTRAP_INTERP" ] && [ ! -e "$NXBOOTSTRAP_INTERP" ]; then
  # The interpreter is absent at the exact path baked into the ELF. Before
  # giving up, look for the SAME loader elsewhere: some CFWs mount their 32-bit
  # runtime off the default path -- spruceOS/Miyoo Flip assembles a 32-bit chroot
  # at boot and copies ld-linux-armhf.so.3 under /usr/lib and /usr/lib32. If we
  # find it, run the game THROUGH that loader with an explicit --library-path
  # (additive: this branch is only reached when the game would otherwise abort).
  NXBOOTSTRAP_INTERP_BASE=$(basename "$NXBOOTSTRAP_INTERP")
  NXBOOTSTRAP_INTERP_ALT=""
  for cand in \
    "/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/usr/lib32/$NXBOOTSTRAP_INTERP_BASE" \
    "/lib32/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/spruce/flip/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/spruce/flip/muOS/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/Persistent/.32bit_chroot/usr/lib/$NXBOOTSTRAP_INTERP_BASE" \
    "/mnt/SDCARD/Persistent/.32bit_chroot/lib/$NXBOOTSTRAP_INTERP_BASE"; do
    [ -e "$cand" ] && { NXBOOTSTRAP_INTERP_ALT="$cand"; break; }
  done
  if [ -n "$NXBOOTSTRAP_INTERP_ALT" ]; then
    # Diretorios confirmados nas IMAGENS oficiais (spruce v4.3.4): o muOS
    # reduzido tem SDL2/EGL/GLES ARMHF em usr/lib (nao so lib32) e o chroot
    # 32-bit monta em /mnt/SDCARD/Persistent/.32bit_chroot.
    NXBOOTSTRAP_INTERP_LIBS="$GAMEDIR:$GAMEDIR/lib:/usr/lib32:/lib32:/mnt/SDCARD/spruce/flip/muOS/usr/lib:/mnt/SDCARD/spruce/flip/muOS/lib:/mnt/SDCARD/spruce/flip/muOS/lib32:/mnt/SDCARD/spruce/flip/muOS/usr/lib32:/mnt/SDCARD/Persistent/.32bit_chroot/usr/lib:/mnt/SDCARD/Persistent/.32bit_chroot/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    NXBOOTSTRAP_INTERP_PREFIX="$NXBOOTSTRAP_INTERP_ALT --library-path $NXBOOTSTRAP_INTERP_LIBS"
    echo "NOTE: interpreter $NXBOOTSTRAP_INTERP is absent at its default path, but $NXBOOTSTRAP_INTERP_ALT exists; launching skate3-nextos through it."
  else
    echo "ERROR: skate3-nextos cannot run here: dynamic loader $NXBOOTSTRAP_INTERP is missing."
    case "$NXBOOTSTRAP_INTERP" in
      *armhf*|*ld-linux.so.3) echo "  32-bit ARM (ARMHF) port, but this CFW has no 32-bit ARM runtime on any known path; use a CFW with 32-bit multiarch (Knulli/ROCKNIX), fix the 32-bit mount (spruce/Miyoo Flip), or use an AArch64 build." ;;
      *aarch64*|*ld-linux-aarch64*) echo "  64-bit ARM (AArch64) port, but this device has no 64-bit ARM runtime." ;;
      *) echo "  this CFW does not provide the runtime this port was built for." ;;
    esac
    nxbootstrap_phase_event preflight ERROR bootstrap 6198 || true
    nxbootstrap_finish
    exit 1
  fi
fi

# Exec bits do not survive zip/FAT/Windows extraction.
$ESUDO chmod +x "$NXBOOTSTRAP_EXECUTABLE" "$GAMEDIR/nxextract-ui" \
  "$GAMEDIR/nxsplash-nextos" "$GAMEDIR"/*.sh 2>/dev/null || true
$ESUDO chmod 666 "$CUR_TTY" /dev/uinput 2>/dev/null || true

# Keep the text console dark across the KMSDRM transition: a slow-loading
# engine (Unity/IL2CPP) would otherwise leave the tty visible -- PortMaster
# get_controls output and boot text -- until its GL window covers the screen,
# and the frontend hand-off already resets it (\033c) on exit. Hide the cursor
# and clear the screen; harmless on fbdev where nothing overlaps.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && \
  printf '\033[?25l\033[2J\033[H' > "$CUR_TTY" 2>/dev/null || true

# One stable lock per port ID, outside the ROM. Replacing the ELF cannot create
# a new lock inode and allow a second game to fight for fb0/audio/input.
NXBOOTSTRAP_LOCK_ROOT=${XDG_RUNTIME_DIR:-}
if [ "${NXBOOTSTRAP_LOCK_ROOT#/}" = "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  NXBOOTSTRAP_LOCK_ROOT=/tmp
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_ROOT=$(cd "$NXBOOTSTRAP_LOCK_ROOT" 2>/dev/null && pwd -P) || {
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
}
case "$NXBOOTSTRAP_LOCK_ROOT" in
  "$GAMEDIR"|"$GAMEDIR"/*)
    echo "ERROR: instance lock directory must be outside the game"
    nxbootstrap_finish
    exit 1
    ;;
esac
NXBOOTSTRAP_LOCK_DIR="$NXBOOTSTRAP_LOCK_ROOT/.nxbootstrap-${UID:-$(id -u)}"
if [ ! -e "$NXBOOTSTRAP_LOCK_DIR" ] && [ ! -L "$NXBOOTSTRAP_LOCK_DIR" ]; then
  (umask 077; mkdir "$NXBOOTSTRAP_LOCK_DIR") 2>/dev/null || true
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_DIR" ] || [ -L "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_DIR" ] || [ ! -w "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_DIR" ] || \
   ! chmod 0700 "$NXBOOTSTRAP_LOCK_DIR" 2>/dev/null; then
  echo "ERROR: unsafe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_FILE="$NXBOOTSTRAP_LOCK_DIR/nxport-skate3.flock"
if [ -e "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ]; then
  if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
     [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ]; then
    echo "ERROR: unsafe instance lock file"
    nxbootstrap_finish
    exit 1
  fi
fi
NXBOOTSTRAP_OLD_UMASK=$(umask)
umask 077
{ exec 9>&-; } 2>/dev/null || true
if ! { exec 9>>"$NXBOOTSTRAP_LOCK_FILE"; } 2>/dev/null; then
  umask "$NXBOOTSTRAP_OLD_UMASK"
  echo "ERROR: cannot open the instance lock"
  nxbootstrap_finish
  exit 1
fi
umask "$NXBOOTSTRAP_OLD_UMASK"
# POSIX/BusyBox/Toybox ls supplies nlink; Bash -ef proves the opened inode.
# Never depend on external stat: some supported muOS images omit it.
NXBOOTSTRAP_LOCK_META=()
IFS=' ' read -r -a NXBOOTSTRAP_LOCK_META \
  <<< "$(LC_ALL=C command ls -Lldn /proc/self/fd/9 2>/dev/null)"
NXBOOTSTRAP_LOCK_LINKS=${NXBOOTSTRAP_LOCK_META[1]:-}
if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ] || [ "$NXBOOTSTRAP_LOCK_LINKS" != 1 ] || \
   ! [ "$NXBOOTSTRAP_LOCK_FILE" -ef /proc/self/fd/9 ]; then
  { exec 9>&-; } 2>/dev/null || true
  echo "ERROR: instance lock identity is unsafe"
  nxbootstrap_finish
  exit 1
fi
unset NXBOOTSTRAP_LOCK_META NXBOOTSTRAP_LOCK_LINKS
if ! flock -n 9; then
  echo "another instance holds the lock; not double-launching"
  nxbootstrap_finish
  exit 1
fi
BIN="$GAMEDIR/skate3-nextos"
# 0.6.24: fonte CANONICA de auto-localizacao do guest. Rodando atraves do
# ld-linux explicito (CFW 64-bit-only com runtime ARMHF fora do caminho), o
# /proc/self/exe do jogo aponta pro LD.SO — loaders que se localizavam por ele
# perdiam a propria pasta (caso de campo: gamedir virou a pasta do loader e o
# preflight recusou). NXBOOTSTRAP_EXE e sempre o caminho REAL do executavel.
export NXBOOTSTRAP_EXE="$BIN"

if command -v pm_platform_helper >/dev/null 2>&1; then
  if pm_platform_helper "$BIN"; then
    echo "pm_platform_helper completed before game launch"
  else
    NXBOOTSTRAP_PLATFORM_STATUS=$?
    echo "WARNING: pm_platform_helper returned status $NXBOOTSTRAP_PLATFORM_STATUS; continuing"
  fi
fi

# A CFW platform module may replace PortMaster's default helper without closing
# the live pugwash dialog. The game then runs (including audio/input) behind the
# dialog's black surface. Act only on PortMaster's exact live FIFO and through
# its own close API; unsafe or unprovable ownership fails before game launch.
NXBOOTSTRAP_DIALOG_PIPE=${PM_PIPE:-}
if [ -n "$NXBOOTSTRAP_DIALOG_PIPE" ] && \
   { [ -e "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; }; then
  if [ ! -p "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; then
    echo "ERROR: PortMaster dialog handoff failed: PM_PIPE is not a live non-symlink FIFO"
    nxbootstrap_finish
    exit 1
  fi
  if ! declare -F PortMasterDialogExit >/dev/null 2>&1; then
    echo "ERROR: PortMaster dialog handoff failed: close API unavailable while PM_PIPE is active"
    nxbootstrap_finish
    exit 1
  fi
  if PortMasterDialogExit; then
    :
  else
    NXBOOTSTRAP_PLATFORM_STATUS=$?
    echo "ERROR: PortMaster dialog handoff failed: close API returned status $NXBOOTSTRAP_PLATFORM_STATUS"
    nxbootstrap_finish
    exit 1
  fi
  if [ -e "$NXBOOTSTRAP_DIALOG_PIPE" ] || [ -L "$NXBOOTSTRAP_DIALOG_PIPE" ]; then
    echo "ERROR: PortMaster dialog handoff failed: PM_PIPE remained after close request"
    nxbootstrap_finish
    exit 1
  fi
  echo "PortMaster dialog closed after platform helper"
fi
unset NXBOOTSTRAP_DIALOG_PIPE NXBOOTSTRAP_PLATFORM_STATUS

nxbootstrap_phase_event preflight OK bootstrap 6191 || {
  nxbootstrap_finish
  exit 1
}


# NXExtract owner-data phase (BYO data): runs before the game, other process.
NXDIR=""
[ -f "$GAMEDIR/nxextract/run-extractor.sh" ] && NXDIR="$GAMEDIR/nxextract"
[ -z "$NXDIR" ] && [ -f "$GAMEDIR/run-extractor.sh" ] && NXDIR="$GAMEDIR"
NXEXTRACT_REQUESTED=1
if [ "$NXEXTRACT_REQUESTED" = 1 ]; then
  nxbootstrap_phase_event nxextract START bootstrap 6200 || {
    nxbootstrap_finish
    exit 1
  }
  NXEXTRACT_INCOMPLETE=0
  [ -n "$NXDIR" ] && [ ! -L "$NXDIR" ] || NXEXTRACT_INCOMPLETE=1
  for nxfile in "$GAMEDIR/extractor.json" "$NXDIR/run-extractor.sh" \
    "$NXDIR/nxextract.py" "$NXDIR/nxextract-runtime-env.sh" \
    "$NXDIR/nxextract-ui"; do
    [ -f "$nxfile" ] && [ -s "$nxfile" ] && [ ! -L "$nxfile" ] || NXEXTRACT_INCOMPLETE=1
  done
  if [ "$NXEXTRACT_INCOMPLETE" = 1 ]; then
    echo "ERROR: incomplete NXExtract integration"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
    nxbootstrap_finish
    exit 1
  fi
  $ESUDO chmod +x "$NXDIR/nxextract-ui" 2>/dev/null || true
  if [ ! -x "$NXDIR/nxextract-ui" ]; then
    echo "ERROR: mandatory NXExtract UI is not executable"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
    nxbootstrap_finish
    exit 1
  fi
  NXEXTRACT_RESULT_FILE="$GAMEDIR/nxextract-result.json"
  if [ -e "$NXEXTRACT_RESULT_FILE" ] || [ -L "$NXEXTRACT_RESULT_FILE" ]; then
    if [ ! -f "$NXEXTRACT_RESULT_FILE" ] || [ -L "$NXEXTRACT_RESULT_FILE" ]; then
      echo "ERROR: stale NXExtract result path is unsafe"
      nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
      nxbootstrap_finish
      exit 1
    fi
    mv -f "$NXEXTRACT_RESULT_FILE" \
      "$GAMEDIR/nxextract-result.prev.json" || {
        echo "ERROR: could not rotate the previous NXExtract result"
        nxbootstrap_phase_event nxextract ERROR bootstrap 6202 || true
        nxbootstrap_finish
        exit 1
      }
  fi
  # The firmware python3 must start: a corrupted stdlib bytecode cache (muOS,
  # "bad marshal data" in encodings) kills it before NXExtract sees the APK.
  # Retry with a private cache, then fail loudly instead of "result malformed".
  NXEXTRACT_PY_PROBE='import encodings, json, zipfile, hashlib'
  if ! python3 -B -c "$NXEXTRACT_PY_PROBE" >/dev/null 2>&1; then
    if PYTHONPYCACHEPREFIX="$GAMEDIR/.nxpycache" python3 -B -c "$NXEXTRACT_PY_PROBE" >/dev/null 2>&1; then
      export PYTHONPYCACHEPREFIX="$GAMEDIR/.nxpycache"
      echo "WARN: system python bytecode cache is broken; using $GAMEDIR/.nxpycache"
    else
      echo "ERROR: the firmware's python3 cannot start (corrupted stdlib/bytecode);"
      echo "ERROR: NXExtract needs a working python3 -- reinstall/update the CFW."
      nxbootstrap_phase_event nxextract ERROR bootstrap 6209 || true
      nxbootstrap_finish
      exit 1
    fi
  fi
  NXEXTRACT_STATUS=0
  NXEXTRACT_GAME_DIR="$GAMEDIR" \
    bash "$NXDIR/nxextract-runtime-env.sh" \
    bash "$NXDIR/run-extractor.sh" || NXEXTRACT_STATUS=$?
  NXEXTRACT_RESULT_STATUS=0
  NXEXTRACT_SUMMARY=""
  if [ -f "$NXEXTRACT_RESULT_FILE" ] && [ ! -L "$NXEXTRACT_RESULT_FILE" ]; then
    if NXEXTRACT_SUMMARY=$(nxbootstrap_validate_nxextract_result \
      "$NXEXTRACT_RESULT_FILE" "$NXEXTRACT_STATUS"); then
      :
    else
      NXEXTRACT_RESULT_STATUS=$?
    fi
  else
    NXEXTRACT_RESULT_STATUS=1
  fi
  if [ "$NXEXTRACT_RESULT_STATUS" -ne 0 ]; then
    echo "ERROR: NXExtract terminal result is missing, unsafe or malformed"
    nxbootstrap_phase_event nxextract ERROR bootstrap 6202 \
      "$NXEXTRACT_STATUS" || true
    nxbootstrap_finish
    if [ "$NXEXTRACT_STATUS" -ne 0 ]; then exit "$NXEXTRACT_STATUS"; fi
    exit 1
  fi
  printf 'NXEXTRACT_RESULT %s\n' "$NXEXTRACT_SUMMARY"
  if [ "$NXEXTRACT_STATUS" -ne 0 ]; then
    echo "ERROR: game data installation did not complete"
    nxbootstrap_phase_event nxextract ERROR extractor 6203 \
      "$NXEXTRACT_STATUS" || true
    nxbootstrap_finish
    exit "$NXEXTRACT_STATUS"
  fi
  nxbootstrap_phase_event nxextract OK extractor 6201 || {
    nxbootstrap_finish
    exit 1
  }
fi
unset NXDIR NXEXTRACT_REQUESTED NXEXTRACT_INCOMPLETE nxfile \
  NXEXTRACT_RESULT_FILE NXEXTRACT_STATUS NXEXTRACT_RESULT_STATUS \
  NXEXTRACT_SUMMARY

# Manifest-owned payload gate: extraction/prepare must finish before launch.
NXBOOTSTRAP_REQUIRED_FILES='skate3-nextos
nxsplash-nextos
lib/libmain.so
lib/libunity.so
lib/libil2cpp.so
assets/bin/Data/boot.config
assets/bin/Data/globalgamemanagers.assets
assets/bin/Data/Managed/Metadata/global-metadata.dat'
while IFS= read -r required_file; do
  [ -n "$required_file" ] || continue
  required_path=$(readlink -f "$GAMEDIR/$required_file" 2>/dev/null) || required_path=""
  case "$required_path" in
    "$GAMEDIR"/*) ;;
    *) required_path="" ;;
  esac
  if [ -z "$required_path" ] || [ ! -f "$required_path" ] || \
     [ ! -s "$required_path" ] || [ -L "$GAMEDIR/$required_file" ]; then
    echo "ERROR: required file is missing or unsafe: $required_file"
    nxbootstrap_finish
    exit 1
  fi
done <<< "$NXBOOTSTRAP_REQUIRED_FILES"
unset NXBOOTSTRAP_REQUIRED_FILES required_file required_path

# Mandatory framework identity handoff: data is complete, native lifecycle has
# not started, and no game-private library path has been added by nxbootstrap.
NXBOOTSTRAP_SPLASH="$GAMEDIR/nxsplash-nextos"
NXBOOTSTRAP_SPLASH_LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.aarch64" \
  /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
  /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
  /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && \
    NXBOOTSTRAP_SPLASH_LIBS="${NXBOOTSTRAP_SPLASH_LIBS:+$NXBOOTSTRAP_SPLASH_LIBS:}$d"
done
echo "nxsplash 0.1.2: mandatory handoff begin"
nxbootstrap_phase_event nxsplash START bootstrap 6204 || {
  nxbootstrap_finish
  exit 1
}
# 0.6.23: em CFW 64-bit-only com o loader ARMHF fora do caminho, TODO ELF
# empacotado precisa do mesmo prefixo que o jogo — o splash executado direto
# morria com o falso "No such file or directory" (status 127) que o proprio
# preflight explica (caso de campo: spruce/Miyoo Flip).
NXBOOTSTRAP_SPLASH_PREFIX=""
if [ -n "${NXBOOTSTRAP_INTERP_PREFIX:-}" ]; then
  NXBOOTSTRAP_SPLASH_INTERP=$(LC_ALL=C grep -a -o -m1 -E '/lib(32|64)?/ld-[A-Za-z0-9._-]*\.so[A-Za-z0-9._-]*' "$NXBOOTSTRAP_SPLASH" 2>/dev/null | head -n1)
  if [ -n "$NXBOOTSTRAP_SPLASH_INTERP" ] && [ ! -e "$NXBOOTSTRAP_SPLASH_INTERP" ]; then
    NXBOOTSTRAP_SPLASH_PREFIX="$NXBOOTSTRAP_INTERP_PREFIX"
    echo "NOTE: nxsplash also runs through the alternate dynamic loader."
  fi
fi
if NX_SPLASH_TTY="${CUR_TTY:-}" \
   LD_LIBRARY_PATH="$NXBOOTSTRAP_SPLASH_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
   $NXBOOTSTRAP_SPLASH_PREFIX "$NXBOOTSTRAP_SPLASH" 'Skateboard Party 3'; then
  echo "nxsplash 0.1.2: mandatory handoff complete"
  nxbootstrap_phase_event nxsplash OK bootstrap 6205 || {
    nxbootstrap_finish
    exit 1
  }
else
  NXBOOTSTRAP_SPLASH_STATUS=$?
  echo "ERROR: mandatory nxsplash failed status=$NXBOOTSTRAP_SPLASH_STATUS"
  nxbootstrap_phase_event nxsplash ERROR bootstrap 6206 \
    "$NXBOOTSTRAP_SPLASH_STATUS" || true
  nxbootstrap_finish
  exit "$NXBOOTSTRAP_SPLASH_STATUS"
fi
unset NXBOOTSTRAP_SPLASH NXBOOTSTRAP_SPLASH_LIBS NXBOOTSTRAP_SPLASH_STATUS \
  NXBOOTSTRAP_SPLASH_PREFIX NXBOOTSTRAP_SPLASH_INTERP d
# HOME preserved (home_mode=preserve).
# An empty CFW mapping must not clobber a valid inherited one (contract:
# honor the existing mapping and only log when the CFW publishes nothing).
[ -n "$sdl_controllerconfig" ] && export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Optional per-port adapter: may export env or replace $BIN / $BIN_PRELOAD.
readonly NXBOOTSTRAP_ANALOG_STICKS_HINT
[ -f "$GAMEDIR/port-env.sh" ] && [ ! -L "$GAMEDIR/port-env.sh" ] && . "$GAMEDIR/port-env.sh"

# Host phase ends here: game/private library paths must never contaminate
# pm_platform_helper or the setup tools above, so they enter only now.
# Firmware/PortMaster overlays first; preserve distro-local providers before
# the system defaults, then append the game's own directory.
LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.aarch64" \
         /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
         /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
         /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && LIBS="${LIBS:+$LIBS:}$d"
done
export LD_LIBRARY_PATH="${LIBS}:$GAMEDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
nxbootstrap_install_exit_trap
nxbootstrap_install_early_traps

# Manifest-owned runtime contract: reassert after every mutable shell hook.
# Reassert after the mutable adapter hook; adapters consume, never redefine it.
NXPORT_LANGUAGE=$NXBOOTSTRAP_LANGUAGE
export NXPORT_LANGUAGE

case "$NXBOOTSTRAP_ANALOG_STICKS_HINT" in
  0|1|2) export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT" ;;
  *) unset NXINPUT_ANALOG_STICKS_HINT ;;
esac
export NXCOMPAT_PORT_ID=skate3
export NXCOMPAT_GAME_DIR="$GAMEDIR"
export NXCOMPAT_REQUIRED_CAPABILITIES='host.portmaster
host.aarch64-libs
graphics.window
graphics.gles2
graphics.egl
graphics.egl-config
graphics.drawable
input.controller-mapping
input.controller-api'
export NXCOMPAT_ENABLED_QUIRKS=''
export NXCOMPAT_RUNTIME_REPORT=log-and-logo

# Guest audio shield (capability-gated, additive): a port whose APK bundles the
# Android OpenAL-soft reads the HOST's /etc/openal/alsoft.conf too. A CFW that
# ships a native `drivers=` line there (AmberELEC ships drivers=alsa) leaves the
# embedded OpenAL with no matching backend -> the game goes SILENT with no error
# (field case: Tightrope on AmberELEC/P4ELEC; reproduced and fix-proven live on
# dArkOSRE by planting that exact file). Pinning ALSOFT_DRIVERS to the OpenSL
# bridge the loader provides neutralizes only that lethal option. Every port
# without the capability keeps a byte-identical environment.
for NXBOOTSTRAP_CAP in $NXCOMPAT_REQUIRED_CAPABILITIES; do
  [ "$NXBOOTSTRAP_CAP" = audio.embedded-openal ] || continue
  export ALSOFT_DRIVERS=opensl
  echo "AUDIO GUEST: ALSOFT_DRIVERS=opensl pinned (embedded OpenAL; host alsoft.conf neutralized)"
  break
done
unset NXBOOTSTRAP_CAP
# One-line receipt of the inherited audio-relevant environment: when a device
# mutes a guest, this line names the suspects without a second round-trip.
echo "ENV RECEIPT: sdl_audiodriver=${SDL_AUDIODRIVER:-} alsoft_drivers=${ALSOFT_DRIVERS:-} alsoft_conf=${ALSOFT_CONF:-} pulse_server=${PULSE_SERVER:-} xdg_runtime_dir=${XDG_RUNTIME_DIR:-}"

game_pid=
NXBOOTSTRAP_CHILD_STARTTIME=
NXBOOTSTRAP_SHUTDOWN_REQUESTED=0
NXBOOTSTRAP_TERM_SENT=0
NXBOOTSTRAP_SIGNAL_COUNT=0
nxbootstrap_capture_child_starttime() {
  local child_stat child_rest
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  NXBOOTSTRAP_CHILD_STARTTIME=${20}
}
nxbootstrap_child_alive() {
  local child_stat child_rest child_state child_start
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || return 1
  builtin kill -0 "$game_pid" 2>/dev/null || return 1
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  child_state=$1
  child_start=${20}
  case "$child_state" in Z|X) return 1 ;; esac
  [ "$child_start" = "$NXBOOTSTRAP_CHILD_STARTTIME" ]
}
nxbootstrap_signal_child() {
  [ "$NXBOOTSTRAP_TERM_SENT" = 0 ] || return 0
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || \
    nxbootstrap_capture_child_starttime || return 0
  nxbootstrap_child_alive || return 0
  NXBOOTSTRAP_TERM_SENT=1
  builtin kill -TERM "$game_pid" 2>/dev/null || true
}
nxbootstrap_request_shutdown() {
  NXBOOTSTRAP_SIGNAL_COUNT=$((NXBOOTSTRAP_SIGNAL_COUNT + 1))
  if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ]; then
    NXBOOTSTRAP_SHUTDOWN_REQUESTED=1
  fi
  nxbootstrap_signal_child || true
}
trap nxbootstrap_request_shutdown INT TERM HUP
# Close the lock fd IN THE CHILD ONLY (9>&-): the launcher keeps fd 9 and the
# flock for the whole game, but the game — and any detached helper it forks —
# must not inherit the lock, or an orphaned grandchild would hold the port lock
# after the launcher exits and block the next launch.
nxbootstrap_phase_event runtime START lifecycle 6207 || {
  nxbootstrap_finish
  exit 1
}
if [ -n "$BIN_PRELOAD" ]; then
  LD_PRELOAD="$BIN_PRELOAD${LD_PRELOAD:+:$LD_PRELOAD}" $NXBOOTSTRAP_INTERP_PREFIX "$BIN" "$GAMEDIR" "$@" 9>&- &
else
  $NXBOOTSTRAP_INTERP_PREFIX "$BIN" "$GAMEDIR" "$@" 9>&- &
fi
game_pid=$!
nxbootstrap_capture_child_starttime || NXBOOTSTRAP_CHILD_STARTTIME=""
[ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ] || nxbootstrap_signal_child
if wait "$game_pid"; then status=0; else status=$?; fi
if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 1 ]; then
  trap '' INT TERM HUP
  NXBOOTSTRAP_SHUTDOWN_TICKS=10
  while [ "$NXBOOTSTRAP_SHUTDOWN_TICKS" -gt 0 ] && nxbootstrap_child_alive; do
    sleep 1 || true
    NXBOOTSTRAP_SHUTDOWN_TICKS=$((NXBOOTSTRAP_SHUTDOWN_TICKS - 1))
  done
  if nxbootstrap_child_alive; then
    echo "== termination deadline expired; sending KILL =="
    builtin kill -KILL "$game_pid" 2>/dev/null || true
  fi
  # Each handled frontend signal can contribute one synthetic 128+n result.
  NXBOOTSTRAP_REWAIT_BUDGET=$NXBOOTSTRAP_SIGNAL_COUNT
  while [ "$NXBOOTSTRAP_REWAIT_BUDGET" -gt 0 ]; do
    case "$status" in 129|130|143) ;; *) break ;; esac
    NXBOOTSTRAP_REWAIT_BUDGET=$((NXBOOTSTRAP_REWAIT_BUDGET - 1))
    if wait "$game_pid" 2>/dev/null; then status=0; else status=$?; fi
  done
else
  # 128+n can also be wait itself being interrupted; recover the child truth.
  while [ "$status" -gt 128 ] && nxbootstrap_child_alive; do
    if wait "$game_pid"; then status=0; else status=$?; fi
  done
fi
nxbootstrap_phase_event runtime EXIT lifecycle 6208 "$status" || \
  echo "WARNING: runtime exit boundary could not be persisted"

# RUNTIME DIAGNOSIS: turn a bare exit code + black screen into one readable
# verdict in the log. Signatures are read from this same log; a clean exit or a
# frontend chord (SIGTERM/SIGKILL) is NOT an error. Never alters $status.
NXBOOTSTRAP_LOG="$GAMEDIR/log.txt"
nxbootstrap_log_has() { [ -r "$NXBOOTSTRAP_LOG" ] && LC_ALL=C grep -qaE "$1" "$NXBOOTSTRAP_LOG" 2>/dev/null; }
NXBOOTSTRAP_DIAG="unclassified — see the log above"
if nxbootstrap_log_has 'undefined symbol:'; then
  NXBOOTSTRAP_DIAG="undefined-symbol — the loader needs a symbol the device library does not export; rebuild against the device SDK ($(LC_ALL=C grep -aoE 'undefined symbol: [A-Za-z0-9_]+' "$NXBOOTSTRAP_LOG" 2>/dev/null | head -n1))"
elif nxbootstrap_log_has 'cannot open shared object'; then
  NXBOOTSTRAP_DIAG="missing-library — a required .so is absent on this CFW; bundle it in the port ($(LC_ALL=C grep -aoE '[A-Za-z0-9._+-]+\.so[A-Za-z0-9._]*: cannot open shared object' "$NXBOOTSTRAP_LOG" 2>/dev/null | head -n1))"
elif [ "$status" = 127 ]; then
  NXBOOTSTRAP_DIAG="status-127 — the executable or its dynamic loader could not be run (missing interpreter/library)"
elif [ "$status" = 139 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGSEGV — the game hit a segfault; read the last frames above for the failing call"
elif [ "$status" = 134 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGABRT — the game aborted itself (assert/abort); the message above names the reason"
elif [ "$status" = 132 ]; then
  NXBOOTSTRAP_DIAG="crash-SIGILL — illegal instruction, usually a wrong-arch or bad-codegen build"
elif nxbootstrap_log_has 'frame proof verdict=(black|absent)' || \
     { nxbootstrap_log_has 'frame proof' && ! nxbootstrap_log_has 'frame proof verdict=OK'; }; then
  NXBOOTSTRAP_DIAG="black-screen — the process ran but no non-black frame was observed; check EGL/GL context and the video receipt above"
elif [ "$status" = 0 ] || [ "$status" = 143 ] || [ "$status" = 137 ] || [ "$status" = 130 ]; then
  NXBOOTSTRAP_DIAG="clean — exited normally or via the frontend/exit chord (status $status)"
else
  NXBOOTSTRAP_DIAG="nonzero-exit (status $status) — the game returned an error; read the log above"
fi
echo "RUNTIME DIAGNOSIS: $NXBOOTSTRAP_DIAG"
echo "== end (status $status) =="

# The game may leave the console keymap off (K_OFF); reset before handing back.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && printf '\033c' > "$CUR_TTY" 2>/dev/null
nxbootstrap_finish
exit $status
